# -*- coding: utf-8 -*-
"""RB's Perceptron

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jk_zGaJPHm822mu-ubwsRWYv3TLRblkk
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

class Perceptron:
    def __init__(self, learning_rate=0.1, n_iterations=100):
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations
        self.weights = None
        self.bias = None

    def activation_function(self, X_input):
        return np.where(X_input >= 0, 1, 0)

    def fit(self, X_input, y_predict):
        n_samples, n_features = X_input.shape
        self.weights = np.zeros(n_features)
        self.bias = 0

        for _ in range(self.n_iterations):
          for i, x_input_i in enumerate(X_input):
              summation_function_output = np.dot(x_input_i, self.weights) + self.bias
              y_predicted = self.activation_function(summation_function_output)

              if y_predict[i] != y_predicted:
                update = self.learning_rate * (y_predict[i] - y_predicted)
                self.weights += update * x_input_i
                self.bias += update

    def predict(self, X_input):
      summation_function_output = np.dot(X_input, self.weights) + self.bias
      return self.activation_function(summation_function_output)

# OR dataset (Single-layer Perceptrons cannot solve XOR)
X_input = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

"""

OR (behaviour)

0 OR 0 = 0
0 OR 1 = 1
1 OR 0 = 1
1 OR 1 = 1

"""

y_predict = np.array([0, 1, 1, 1])

perceptron = Perceptron()
perceptron.fit(X_input, y_predict)
predictions = perceptron.predict(X_input)

# print outputs
print(f"Predictions: {predictions}")
print(f"Actuals:     {y_predict}")
print(f"Accuracy:    {np.mean(predictions == y_predict) * 100}%")

def plot_decision_boundary(X_input, y_predict, perceptron):
  # Define Orange and Blue colors
  # 0 = Orange (#ff7f0e), 1 = Blue (#1f77b4)
  custom_cmap = ListedColormap(['#ff7f0e', '#1f77b4'])

  x_min, x_max = X_input[:, 0].min() - 0.5, X_input[:, 0].max() + 0.5
  y_min, y_max = X_input[:, 1].min() - 0.5, X_input[:, 1].max() + 0.5

  xx, yy = np.meshgrid(np.arange(x_min, x_max, 0.01), np.arange(y_min, y_max, 0.01))

  Z = perceptron.predict(np.c_[xx.ravel(), yy.ravel()])
  Z = Z.reshape(xx.shape)

  plt.figure(figsize=(10, 6))

  # Plot the decision regions using the custom orange-blue map
  plt.contourf(xx, yy, Z, alpha=0.3, cmap=custom_cmap)

  # Plot the training points
  # edgecolors='k' adds a black outline to the dots for better visibility
  scatter = plt.scatter(X_input[:, 0], X_input[:, 1], c=y_predict,
                        cmap=custom_cmap, edgecolors='k', s=100)

  plt.xlabel('Feature 1')
  plt.ylabel('Feature 2')
  plt.title('Perceptron Decision Boundary (OR Gate)')

  # Add a legend
  handles, labels = scatter.legend_elements()
  plt.legend(handles, ['Class 0 (Orange)', 'Class 1 (Blue)'], loc="upper left")

plot_decision_boundary(X_input, y_predict, perceptron)
plt.show()